### ISSUE TITLE
Distorted/broken rendering on Linux with Nvidia card

### ISSUE THREAD

**Issue by christoph-heiss** [fintelia/terra#13]
Hi!

Running master (commit 4d4600c) this on my Linux box gives me the following picture:
![Screenshot from 2021-01-25 16-33-59](https://user-images.githubusercontent.com/7571069/105727812-bcc21300-5f2b-11eb-810a-0202d3234e58.png)

The system is a fully up-to-date Arch Linux; kernel `5.10.10-arch1-1`, nvidia driver `460.32.03-6` on a  Nvidia GTX 970.
Also tried removing `~/.cache/terra` and re-running it with nightly, which gave the same result.

I'd be happy to help investigate this further if needed!

**Comment by fintelia** [comment]
Thanks for reporting this! I just tested with a spare Nvidia GPU and was able to reproduce the issue. From some initial debugging it seems this is a bug in wgpu, so I'll try reporting to them shortly
