### ISSUE TITLE
locked up screen

### ISSUE THREAD

**Issue by gedw99** [fintelia/terra#16]
on mac with 16 gb ram and integrated gpu.

When i ran the demo my Mac completely locked up, and the game moved one frame in 1 minute.

Not sure what is causing it.

**Comment by fintelia** [comment]
As a guess, does your Mac also have a very high resolution display? I just experimented some on my laptop with an integrated GPU and found it was spending most of its time running pixel shaders.

Could you try running [this branch](https://github.com/fintelia/terra/tree/no-scattering) and see if performance is any better?
