### ISSUE TITLE
Panic on startup

### ISSUE THREAD

**Issue by PureTryOut** [fintelia/terra#26]
```
05:26 terra (main) cargo run --release
    Finished release [optimized + debuginfo] target(s) in 0.24s
     Running `target/release/preview`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/mapfile.rs:156:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

First I thought it was an old cache but after `rm -r ~/.cache/terra` it downloaded everything and afterwards just started to panic like before again.

**Comment by fintelia** [comment]
The program wasn't downloading one of the textures required to run, which caused a panic when it tried to open it but found the file didn't exist. Please feel free to reopen if you're still seeing issues
