### ISSUE TITLE
How do you set this up?

### ISSUE THREAD

**Issue by MaxTD** [fintelia/terra#5]

**Comment by fintelia** [comment]
If you already have a nightly version of Rust installed via [rustup](https://rustup.rs/), then it should just be a matter of cloning the repository and then executing:

`cargo +nightly run --example preview --release`

I've only tested on Linux, though it may work on other platforms. Please post issues if you run into any problems.

A warning though: The first time it is run terra will download many gigabytes worth of datasets from the internet to ~/.cache/terra, and then spend a while processing them into a map file it can use. If interrupted during the process it can generally resume where it left off, but the whole thing can take 30+ minutes (more on a slow connection)
