### ISSUE TITLE
Crash on writing heightmaps, dead link?

### ISSUE THREAD

**Issue by pjentsch0** [fintelia/terra#7]
Hi,

I was trying to test this out, looks like a really cool project.

I clone the repo and ran,
```
cargo +nightly run --release
```

The project compiles but crashes after outputting this:

```
Writing heightmaps... 0 / 130559 [            ] 0.00 %
Downloading dems/srtm3/n35_e134.hgt.s...0 / 100  0.00 %
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/peterj/Projects/terra/src/generate/heightmap.rs:407:71
```

**Comment by fintelia** [comment]
The URL must have changed. I'll see if I can find a new one.

In the slightly longer term, I'm looking into whether I can host the tiles myself so everyone doesn't have to download the datasets and generate them themselves.
